- uses: webbertakken/unity-builder@<version>
  env:
    UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  with:
    projectPath: path/to/your/project
    unityVersion: 2019.4.11f1
    targetPlatform:
          - StandaloneWindows # Build a Windows standalone.

  uses: actions/upload-artifact@v1
     with:
        name: Build
        path: build
